spring:
  datasource:
    url: jdbc:mysql://<url>:3306/<db_name>
    username: <username>
    password:  <password>
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  social:
    facebook:
      appId: 821156638448534
      appSecret: f9fc6815f618911d6a49af1a902ea499
  mail:
    host: <smtp_host>
    username: <username>
    password: <password>
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  token:
    validity: 594000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization
  secret: signinkey

server:
  port: 8084