spring:
  datasource:
    url: jdbc:mysql://localhost:3306/se2
    username: root
    password: ?Giugno98
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  social:
    facebook:
      appId: 821156638448534
      appSecret: f9fc6815f618911d6a49af1a902ea499
  #mvc:
  #  static-path-pattern: /content/**
jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization
  secret: signinkey
